edit ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,29 +22,48 @@ jobs:
 #        run: |
 #          cd app && python3 -m pytest
 #
-  docker-up:
-    runs-on: ubuntu-latest
+#  docker-up:
+#    runs-on: ubuntu-latest
 #    needs: test-code
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v5
+#
+#      - name: Setup Docker
+#        uses: docker/setup-buildx-action@v2
+#
+#      - name: Build and Start containers
+#        run: docker compose up -d
+#
+#      - name: curl localhost
+#        run: |
+#          for i in {1..5}; do
+#            if curl --fail http://localhost > /dev/null; then
+#              echo "Flask is up!"
+#              exit 0
+#            else
+#              sleep 2
+#            fi
+#          done
+#
+#          echo "Flask not ready!"
+#          exit 1
+
+  push-registry:
+    runs-on: ubuntu-latest
+    needs: test-code
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v5
 
-      - name: Setup Docker
-        uses: docker/setup-buildx-action@v2
+      - name: Login to GHCR
+        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-      - name: Build and Start containers
-        run: docker compose up -d
-
-      - name: curl localhost
+      - name: Build Docker image
         run: |
-          for i in {1..5}; do
-            if curl --fail http://localhost > /dev/null; then
-              echo "Flask is up!"
-              exit 0
-            else
-              sleep 2
-            fi
-          done
+          docker build -t ghcr.io/${{ github.repository }}:test ./app
 
-          echo "Flask not ready!"
-          exit 1
+      - name: Push image
+        run: |
+          docker push ghcr.io/${{ github.repository }}:test
